# 自定义配置文件
head:
  # 是否需要精确匹配
  accurate: false
  # 表头颜色
  color:
  # 表头格式
  pattern: .*(?i)(every).*
  # 是否需要解析
  parsing: false
  # 范围
  range: 1


content:
  titleSign:
    color: 255,204,153
    pattern:
  # 通用属性
  universal: vesselName(2),carrierVoyageNo(1),cyOpeningTime(1),cyCutOffTime(1),siCutOffTime(1),vgmCutOffTime(1),etd(1)
  # 可变属性
  special: 抵港日期(ETA)

tail:
  # 是否需要精确匹配
  accurate: false
  # 表尾颜色
  color:
  # 表尾格式
  pattern: .*DR CUT OFF.*
  # 是否需要解析
  parsing: false
  # 范围
  range: 1